# Generated by Django 3.0 on 2021-08-23 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.AlterModelTable(
            name='profile',
            table=None,
        ),
    ]
